apiVersion: v1
kind: Namespace
metadata:
  name: sec-app
  labels:
    name: sec-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sec-app
  name: "sec-app"
spec:
  selector:
    matchLabels:
      app: "sec-app"
  template:
    metadata:
      name: "sec-app"
    spec:
      containers:
        - name: "sec-app"
          image: "app-image"
      serviceAccountName: "sec-app-sa"