apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- "deployment.yaml"
images:
- name: "app-image"
  newName: "gjensidige.azurecr.io/your-team-name/your-app-name"
  newTag: "initial"
namespace: "your-team-namespace"
