apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: sec-app
  labels:
    app: mongo-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-todo
      tier: backend
  template:
    metadata:
      labels:
        app: mongo-todo
        tier: backend
    spec:
      serviceAccountName: sec-app-sa
      containers:
        - name: web
          image: us-central1-docker.pkg.dev/clgcporg10-170/sec-app/app:94dd13e67f7fbff4c3c7a1eacd3ee17b8917a733
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: MONGODB_URI
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000