name: Trivy Terraform Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy config scan on Terraform
        uses: aquasecurity/trivy-action@0.28.0 # Use the latest version
        with:
          scan-type: 'config'
          scan-ref: './gitops/app/base/k8s'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH' # Optional: Filter by severity

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
